# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-19 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_password', models.CharField(max_length=100)),
                ('account_email', models.CharField(blank=True, max_length=100, verbose_name='e-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=12)),
                ('character_date', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=20)),
                ('job_story', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=20)),
                ('race_story', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='race',
            field=models.ManyToManyField(to='creation.Race'),
        ),
        migrations.AddField(
            model_name='character',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.Job'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.Race'),
        ),
    ]
