# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-20 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0003_auto_20190519_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Hair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='character_name',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='character',
            name='color',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='creation.Color'),
        ),
        migrations.AddField(
            model_name='character',
            name='face',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='creation.Face'),
        ),
        migrations.AddField(
            model_name='character',
            name='hair',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='creation.Hair'),
        ),
    ]
