# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-20 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0004_auto_20190520_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_name', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='sex',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='creation.Sex'),
        ),
    ]
