# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-21 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0005_auto_20190520_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['account']},
        ),
        migrations.AddField(
            model_name='character',
            name='character_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
