# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-21 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0006_auto_20190521_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['account', 'character_name']},
        ),
    ]
