# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-21 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0007_auto_20190521_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.Job', verbose_name='Class'),
        ),
    ]
